[workspace.package]
authors = ["Parity Technologies <admin@parity.io>"]
edition = "2021"
repository = "https://github.com/paritytech/polkadot-sdk.git"
license = "GPL-3.0-only"

[workspace]
resolver = "2"
members = [
	"utils/funder",
	"utils/sender",
	"stps"
]

default-members = ["stps"]

[workspace.dependencies]
sp-core = "31.0.0"
sp-runtime = "32.0.0"
sp-keyring = "32.0.0"
subxt = { version = "0.38.1", features = ["substrate-compat"] }
frame-system = "31.0.0"
pallet-balances = "31.0.0"
reqwest = "0.11"
