FROM rust:latest as builder

COPY . /build

WORKDIR /build/utils/funder

RUN cargo build

FROM docker.io/library/ubuntu:20.04

COPY --from=builder /build/utils/funder/target/debug/funder /usr/local/bin

RUN useradd -m -u 1000 -U -s /bin/sh -d /funder funder

USER funder

ENTRYPOINT [ "/usr/local/bin/funder" ]
