FROM rust:latest as builder

COPY . /build

WORKDIR /build/utils/sender

# ARG feature_flag

# ENV FEATURE=${feature_flag}

# RUN cargo build --features=$FEATURE --release

RUN cargo build --release

FROM docker.io/library/ubuntu:20.04

COPY --from=builder /build/utils/sender/target/debug/sender /usr/local/bin

RUN useradd -m -u 1000 -U -s /bin/sh -d /sender sender

USER sender

ENTRYPOINT [ "/usr/local/bin/sender" ]
