name: Build and Publish Docker containers

on:
  push:
    branches:
      - main

jobs:
  funder:
    name:                         Build and push funder image
    runs-on:                      ubuntu-latest
    steps:
    - uses:                       actions/checkout@v4
    - name:                       Build Image
      uses:                       redhat-actions/buildah-build@v2
      with:
        image:                    stps-funder
        tags:                     funder-latest
        dockerfiles: |
          ./utils/dockerfiles/Dockerfile.funder
        build-args: |
          VCS_REF=${{ github.ref }}
          BUILD_DATE=${{ github.event.release.published_at }}

    - name:                       Push image to docker.io
      id:                         push-to-dockerhub
      uses:                       redhat-actions/push-to-registry@v2
      with:
        registry:                 docker.io/paritytech
        image:                    stps-funder
        tags:                     funder-latest
        username:                 ${{ secrets.DOCKERHUB_USERNAME }}
        password:                 ${{ secrets.DOCKERHUB_TOKEN }}

    - name:                       Check the image
      run: |
        echo "New image has been pushed to ${{ steps.push-to-dockerhub.outputs.registry-path }}"
  
  sender:
    name:                         Build and push sender image
    runs-on:                      ubuntu-latest
    steps:
    - uses:                       actions/checkout@v4
    - name:                       Build Image
      uses:                       redhat-actions/buildah-build@v2
      with:
        image:                    stps-sender
        tags:                     sender-latest
        dockerfiles: |
          ./utils/dockerfiles/Dockerfile.sender
        build-args: |
          CHAIN=tick
          VCS_REF=${{ github.ref }}
          BUILD_DATE=${{ github.event.release.published_at }}

    - name:                       Push image to docker.io
      id:                         push-to-dockerhub
      uses:                       redhat-actions/push-to-registry@v2
      with:
        registry:                 docker.io/paritytech
        image:                    stps-sender
        tags:                     sender-latest
        username:                 ${{ secrets.DOCKERHUB_USERNAME }}
        password:                 ${{ secrets.DOCKERHUB_TOKEN }}

    - name:                       Check the image
      run: |
        echo "New image has been pushed to ${{ steps.push-to-dockerhub.outputs.registry-path }}"
  
