name: E2E sTPS Test

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v5
      # toolchain
      - name: Install toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: nightly-2022-06-30
          components: rustfmt, clippy
          target: wasm32-unknown-unknown
          override: true
          default: true
      # zombienet
      - name: Run zombienet
        run: |
          ./polkadot-stps.sh test_native tests/native/relay-single-node-native.zndsl
